### ISSUE TITLE
Tauri setup on Ubuntu 24.04

### ISSUE THREAD

**Issue by offtherailz** [ziriuz84/asteroid_app#34]
During my dev setup on Ubuntu 24.04 I encountered some issues with libs (looks to be similar to the ones  [here](https://github.com/tauri-apps/tauri/issues/3701) and [here](https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2692597564))

When trying to apply the workarounds or installing the dependencies, I found another error: 

```
 libxfixes-dev : Depends on: libxfixes3 (= 1:6.0.0-2build1) but the version 1:6.0.0-9~ubuntu20.04 is going to be installed
```

For this reason I'm going to try to use docker:

Here my docker file

```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libwebkit2gtk-4.1-dev \
    curl \
    wget \
    file \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev\
    librsvg2-dev \
    build-essential \
    # node 18 da NodeSource
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt install -y nodejs

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN npm install -g pnpm

WORKDIR /app
COPY . .

RUN pnpm install || npm install
RUN npm run tauri build

```

It's almost running but at the end I have the following error: 

```
[...]
144.0    Compiling tauri-plugin v2.0.2
144.1 error[E0308]: mismatched types
144.1    --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-plugin-2.0.2/src/build/mod.rs:140:58
144.1     |
144.1 140 |       tauri_utils::plugin::define_global_api_script_path(path);
144.1     |       -------------------------------------------------- ^^^^ expected `&Path`, found `PathBuf`
144.1     |       |
144.1     |       arguments to this function are incorrect
144.1     |
144.1 note: function defined here
144.1    --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-utils-2.3.1/src/plugin.rs:22:10
144.1     |
144.1 22  |   pub fn define_global_api_script_path(path: &Path) {
144.1     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
144.1 help: consider borrowing here
144.1     |
144.1 140 |       tauri_utils::plugin::define_global_api_script_path(&path);
144.1     |                                                          +
144.1 
144.1 For more information about this error, try `rustc --explain E0308`.
144.1 error: could not compile `tauri-plugin` (lib) due to 1 previous error
144.1 warning: build failed, waiting for other jobs to finish...
156.0 failed to build app: failed to build app
156.0        Error failed to build app: failed to build app
------
failed to solve: process "/bin/sh -c npm run tauri build" did not complete successfully: exit code: 1
```

Any clue about how to solve this last issue @ziriuz84 ? If so I'll be happy to contribute with docker file and docker compose to make the build (and dev) env run in a dockerized way.

My final idea was to build in docker and then allow to run via docker compose the dev environment, with something like:

```yml
version: "3.8"

services:
  tauri-dev:
    build: .
    container_name: tauri-dev
    volumes:
      - .:/app
    #  - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    # - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    command: npm run tauri dev
    ports:
      - "1420:1420"  # Espone la porta 1420
```
